#Ansible Playbook to install Monitoring agent, Java and Tomcat Server
---
- name: Deploy Tomcat and Datadog agent
  hosts: 'all'
  become: yes
  become_method: sudo
  tasks:
    - name: Update all packages
      apt:
        name: "*"
        state: latest

    - name: Install basic packages
      apt:
        name: ['vim', 'htop', 'tmux', 'screen', 'telnet', 'wget', 'curl', 'git']
        state: present

    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes

    - name: Install OpenJDK Java
      become: yes
      apt:
        name: openjdk-8-jdk
        state: present
      with_items:
        openjdk-8-jdk

- name: Install datadog angent on hosts
  hosts: all
  roles:
    - { role: Datadog.datadog, become: yes }
  vars:
     datadog_api_key: "{{ lookup('env', 'API_KEY') }}"
     datadog_config:
       tags:
         - env:dev
       logs_enabled: true
       process_config:
         enabled: "true"
        
