name: Building a Simple WebApp
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn clean install -f MyWebApp/pom.xml
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with:
        java-version: 1.8
     - name: Run the Maven verify phase
       run: mvn -B verify --file MyWebApp/pom.xml      
  Deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "Deploy artifact to Tomcat Server"                              # I was unable to setup the tomcat server, hence I could not achieve the desired goal. The idea is to deploy this application to a remote tomcat server built with Terraform
